#! /usr/bin/env bash

declare choice

if [[ -z "${PREFIX}" ]] ; then
	echo 'PREFIX not set. Do you wish to continue with PREFIX=/usr/local?'
	select choice in yes no ; do
		case "${choice}" in
			y|yes)
				PREFIX='/usr/local'
				break
				;;
			n|no)
				echo 'Aborting installation.'
				exit 1
				;;
			*)
				echo 'Please select a numbered option.'
				;;
		esac
	done
fi

if ! [[ -e "${PREFIX}"/bin ]] ; then
	mkdir -p "${PREFIX}"/bin
fi

if ! [[ -e "${PREFIX}"/share/man/man1 ]] ; then
	mkdir -p "${PREFIX}"/share/man/man1
fi

cp git-branch-data "${PREFIX}"/bin/git-branch-data
chmod +x "${PREFIX}"/bin/git-branch-data

cp git-branch-data.1 "${PREFIX}"/share/man/man1/git-branch-data.1
gzip -f "${PREFIX}"/share/man/man1/git-branch-data.1

echo 'Installation complete.'
exit 0
